language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "cpanm Module::Install"
  - ./dev-bin/travis-prepare.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true

